#!/bin/bash
# Redshift 
redshift -O 4500 &
# /home/oscar/.config/suckless/dwm-bar/dwm_bar.sh &
slstatus &
xsetroot -solid black & 
copyq &
dunst &
/home/oscar/.config/suckless/batCheck.sh &
# Change keyboard layout automatically
setxkbmap -layout latam,latam & 
# Fix Wi-Fi not turning on automatically
#nmcli radio wifi on &
dwm
